services:
  mongodb:
    container_name: api-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db # Enables persistent data storage
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    stop_grace_period: 1s

  ccn-coverage-api:
    container_name: api-api
    build: .
    ports:
      - '$COVERAGE_API_PORT:$COVERAGE_API_PORT'
    depends_on:
      - mongodb # Ensure API waits for MongoDB to be ready
    volumes:
      - ./keys:/usr/src/app/keys
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/api-data # Set the MongoDB URI environment variable for the API
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:$COVERAGE_API_PORT/api/sites']
      interval: 10m
      timeout: 30s
      retries: 10
      start_period: 30s
    stop_grace_period: 1s

volumes:
  mongodb_data: # Named volume that will store MongoDB data
