services:
  ccn-coverage-api:
    container_name: ccn-coverage-api
    image: ccn-coverage-api:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/api-data
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-db:/data/db
      - mongo-data-configdb:/data/configdb
      - ${PWD}/mock/mongo:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data-db:
  mongo-data-configdb:

networks:
  app-network:
    driver: bridge