services:
  api:
    container_name: api
    image: ccn-coverage-api:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/api-data
      - LDAP_URI=ldap://ldap:389
    depends_on:
      - mongodb
      - ldap
    restart: unless-stopped
    networks:
      - coverage-app-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-db:/data/db
      - mongo-data-configdb:/data/configdb
      - ${PWD}/mock/mongo:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - coverage-app-network
  
  ldap:
    build: ./mock/ldap
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "SCN"
      LDAP_DOMAIN: "seattlecommunitynetwork.org"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_CONFIG_PASSWORD: "config_password"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    restart: unless-stopped
    networks:
      - coverage-app-network

volumes:
  mongo-data-db:
  mongo-data-configdb:
  ldap_data:
  ldap_config:

networks:
  coverage-app-network:
    driver: bridge